#!/usr/bin/env bash


[ -d ".git" ] || (echo "Fatal: not a git repository" && exit 1)


# mkdir -p .incremental # add to .gitignore ?

start() {
  INC_DIR=$(pwd)
  INC_ID=$(ls -di $(pwd) | cut -f 1 -d " ")
  cd $(dirname $0)/..
  mkdir -p local
  echo $INC_DIR $INC_ID
  echo "Incremental will be running shortly."
  lein run $INC_DIR $INC_ID > local/log 2>&1 &
}

stop() {
  INC_DIR=$(pwd)
  INC_ID=$(ls -di $(pwd) | cut -f 1 -d " ")

  cd $(dirname $0)/..
  mkdir -p local/stop
  echo "Incremental will stop running shortly."
  echo $INC_ID
  touch local/stop/$INC_ID
}

#instruct() {
#  echo $@ >> ~/.incremental/instructions
#}

case "$1" in
  stop)   stop;;
  start)  start;;
  "")     start;;
  *)      echo "Usage: inc [start|stop] (defaults to start if no arg passed)"; exit 1;;
esac



