#!/usr/bin/env bash

mkdir -p ~/.incremental

start() {
  cd $(dirname $0)/..
  echo "Incremental will be running shortly."
  lein run > ~/.incremental/log 2>&1 &
}

instruct() {
  echo $@ >> ~/.incremental/instructions
}

case "$1" in
  add)    instruct "+ $(pwd)";;
  remove) instruct "- $(pwd)";;
  stop)   instruct "! Cease.";;
  start)  start;;
  "")     start;;
  *)      echo "Usage: inc [add|remove|start|stop] (defaults to start if no arg passed)"; exit 1;;
esac

